apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.configMap.name . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  enableTool: "{{ .Values.configMap.enableTool }}"
