deployment:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  image:
    repository: us-central1-docker.pkg.dev/<PROJECT-ID>/<ARTIFACTORY-NAME>/<IMAGE-NAME>
    tag: latest
    pullPolicy: IfNotPresent

service:
  name: image-blur-svc
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  name: image-blur-ingress
  className: ""
  annotations: {}
  hosts:
    - host: blur-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

configMap:
  name: image-blur-config
  enableTool: "true"
